steps:

  # Install dependencies
  - name: 'python:3.8'
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--no-cache', '-t', '${_IMAGE_NAME}', '.' ]
    id: 'build'

#  # Push the container image to Container Registry
#  - name: 'gcr.io/cloud-builders/docker'
#    args: [ 'push', '${_IMAGE_NAME}' ]
#    id: 'push'
#    waitFor: ['build']

  # Compile pipeline
#  - name: 'python:3.8'
#    entrypoint: 'python'
#    args: ['pipeline.py']
#    id: 'compile'
#    waitFor: ['push']

  # Upload compiled pipeline to GCS.
#  - name: 'gcr.io/cloud-builders/gsutil'
#    args: ['cp', 'dbscan_pipeline.json', 'gs://nashtech_vertex_ai_artifact']
#    id:  'upload'
#    waitFor: ['compile']

  # Trigger and create the pipeline
#  - name: 'python:3.8'
#    entrypoint: 'python'
#    args: ['pipeline_run.py']
#    id: 'run_pipeline'
#    waitFor: ['upload']

substitutions:
  TAG_NAME: "0.0.1"
  _IMAGE_NAME: 'us-central1-docker.pkg.dev/nashtech-ai-dev-389315/clustering-pipeline/db-scan-image-$SHORT_SHA:$TAG_NAME'


options:
  dynamicSubstitutions: true
  logging: CLOUD_LOGGING_ONLY
