steps:

  - name: 'gcr.io/cloud-builders/gsutil'
    args: [ 'cp', 'gs://clustering-pipeline-artifact/tag_details.json', 'serving_container/pipeline_image_configuration.json' ]
    id: 'tag_file'

  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update
        apt-get install -y jq
        export _BUILD_TAG="$(jq -r 'image_tag' serving_container/tag_details.json)"
    id: 'extract_tag'
    waitFor: [ 'tag_file' ]

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--no-cache', '-t', '${_IMAGE_NAME}:$_BUILD_TAG_$SHORT_SHA, '.' ]
    id: 'build'
    waitFor: ['extract_tag']

substitutions:
  _IMAGE_NAME: 'us-central1-docker.pkg.dev/nashtech-ai-dev-389315/clustering-pipeline/db-scan-image'

options:
  dynamicSubstitutions: true
  logging: CLOUD_LOGGING_ONLY
