steps:

  # Install dependencies
  - name: 'python:3.8'
    entrypoint: pip
    args: [ "install", "-r", "serving_container/requirements.txt", "--user" ]
    id: 'requirements'

  # Download _TAG File from GCS
  - name: 'gcr.io/cloud-builders/gsutil'
    args: [ 'cp', 'gs://clustering-pipeline-artifact/_TAG', 'serving_container/' ]
    id: 'upload'
    waitFor: [ 'write' ]

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'sh'
    args: [ '-c', 'docker build . -t ${_IMAGE_NAME}:$(cat serving_container/_TAG) -f serving_container/Dockerfile' ]
    id: 'build'
    waitFor: [ 'upload' ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'sh'
    args: [ '-c', 'docker push ${_IMAGE_NAME}:$(cat serving_container/_TAG)' ]
    id: 'push'
    waitFor: [ 'build' ]

substitutions:
  _IMAGE_NAME: 'us-central1-docker.pkg.dev/nashtech-ai-dev-389315/clustering-pipeline/dbscan-serve-image'

options:
  dynamicSubstitutions: true
  logging: CLOUD_LOGGING_ONLY

