steps:

  # Install dependencies
  - name: 'python:3.8'
    entrypoint: pip
    args: [ "install", "-r", "serving_container/requirements.txt", "--user" ]
    id: 'requirements'

    # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--no-cache', '-t', '${_IMAGE_NAME}', '.' ]
    id: 'build'
    waitFor: ['requirements']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', '${_IMAGE_NAME}' ]
    id: 'push'
    waitFor: ['build']

substitutions:
  TAG_NAME: 'latest'
  _IMAGE_NAME: 'us-central1-docker.pkg.dev/nashtech-ai-dev-389315/clustering-pipeline/dbscan-serve-image:${SHORT_SHA}-${TAG_NAME}'

options:
  dynamicSubstitutions: true
  logging: CLOUD_LOGGING_ONLY

