steps:

  # Install dependencies
  - name: 'python:3.8'
    entrypoint: pip
    args: [ "install", "-r", "serving_container/requirements.txt", "--user" ]
    id: 'requirements'

  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'sh'
    args: [ '-c', 'docker build . -t ${_IMAGE_NAME} -f serving_container/Dockerfile' ]
    id: 'build'
    waitFor: ['requirements']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'sh'
    args: [ '-c', 'docker push ${_IMAGE_NAME}' ]
    id: 'push'
    waitFor: [ 'build' ]

substitutions:
  _IMAGE_NAME: 'us-central1-docker.pkg.dev/nashtech-ai-dev-389315/clustering-pipeline/db-scan-image:${SHORT_SHA}'

options:
  dynamicSubstitutions: true
  logging: CLOUD_LOGGING_ONLY

