steps:

  # Install dependencies
  - name: 'python:3.8'
    entrypoint: pip
    args: [ "install", "-r", "serving_container/requirements.txt", "--user" ]

  # Download the configuration file from gcs
  - name: 'gcr.io/cloud-builders/gsutil'
    args: [ 'cp', 'gs://clustering-pipeline-artifact/pipeline_image_configuration.json', 'serving_container/pipeline_image_configuration.json' ]
    id: 'tag_file'

  # Extract the image tag from json file
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        apt-get update
        apt-get install -y jq
        echo "$(jq -r 'image_tag' serving_container/pipeline_image_configuration.json)"
    id: 'extract_tag'
    waitFor: ['tag_file']

  # Build the serving container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '.', '-t', '${_IMAGE_NAME}:${TAG_NAME}', '-f', 'serving_container/Dockerfile' ]
    id: 'build'
    waitFor: ['extract_tag']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', '${_IMAGE_NAME}:${TAG_NAME}' ]
    id: 'push'
    waitFor: ['build']


substitutions:
  _IMAGE_NAME: 'us-central1-docker.pkg.dev/nashtech-ai-dev-389315/clustering-pipeline/dbscan-serve-image-${SHORT_SHA}'


options:
  dynamicSubstitutions: true
  logging: CLOUD_LOGGING_ONLY

